[phases.setup]
nixPkgs = ["python39", "gcc", "libffi", "openssl", "postgresql"]

[phases.install]
cmds = ["pip install --upgrade pip setuptools wheel", "pip install -r requirements.txt"]

[start]
cmd = "python manage.py migrate && python manage.py seed_data && gunicorn breathe_esg.wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
